/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BootRouteImport } from './routes/boot'
import { Route as WorkspacesRouteRouteImport } from './routes/workspaces/route'
import { Route as MenuRouteRouteImport } from './routes/menu/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as MenuTrashRouteImport } from './routes/menu/trash'
import { Route as MenuSettingsRouteImport } from './routes/menu/settings'
import { Route as MenuConflictsRouteImport } from './routes/menu/conflicts'
import { Route as DashboardWorkspaceIdRouteRouteImport } from './routes/dashboard/$workspaceId/route'
import { Route as DashboardWorkspaceIdIndexRouteImport } from './routes/dashboard/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdEditRouteImport } from './routes/workspaces/$workspaceId.edit'
import { Route as DashboardWorkspaceIdCreateEntityKindRouteImport } from './routes/dashboard/$workspaceId/create.$entityKind'
import { Route as DashboardWorkspaceIdFoldersFolderIdRouteRouteImport } from './routes/dashboard/$workspaceId/folders/$folderId/route'
import { Route as DashboardWorkspaceIdDecksDeckIdRouteRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/route'
import { Route as DashboardWorkspaceIdFoldersFolderIdIndexRouteImport } from './routes/dashboard/$workspaceId/folders/$folderId/index'
import { Route as DashboardWorkspaceIdDecksDeckIdIndexRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/index'
import { Route as DashboardWorkspaceIdFoldersFolderIdEditRouteImport } from './routes/dashboard/$workspaceId/folders/$folderId/edit'
import { Route as DashboardWorkspaceIdDecksDeckIdEditRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/edit'
import { Route as DashboardWorkspaceIdDecksDeckIdReviewRouteRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/review/route'
import { Route as DashboardWorkspaceIdDecksDeckIdNotesRouteRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/notes/route'
import { Route as DashboardWorkspaceIdDecksDeckIdReviewIndexRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/review/index'
import { Route as DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRouteImport } from './routes/dashboard/$workspaceId/folders/$folderId/create.$entityKind'
import { Route as DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/review/$reviewId/route'
import { Route as DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/notes/$noteId/route'
import { Route as DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/review/$reviewId/index'
import { Route as DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/notes/$noteId/index'
import { Route as DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
import { Route as DashboardWorkspaceIdDecksDeckIdNotesNewKindRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/notes/new.$kind'
import { Route as DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRouteImport } from './routes/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'

const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRouteRoute = WorkspacesRouteRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRouteRoute = MenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRouteRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRouteRoute,
} as any)
const MenuTrashRoute = MenuTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuSettingsRoute = MenuSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuConflictsRoute = MenuConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => MenuRouteRoute,
} as any)
const DashboardWorkspaceIdRouteRoute =
  DashboardWorkspaceIdRouteRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWorkspaceIdIndexRoute =
  DashboardWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdEditRoute =
  WorkspacesWorkspaceIdEditRouteImport.update({
    id: '/$workspaceId/edit',
    path: '/$workspaceId/edit',
    getParentRoute: () => WorkspacesRouteRoute,
  } as any)
const DashboardWorkspaceIdCreateEntityKindRoute =
  DashboardWorkspaceIdCreateEntityKindRouteImport.update({
    id: '/create/$entityKind',
    path: '/create/$entityKind',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdFoldersFolderIdRouteRoute =
  DashboardWorkspaceIdFoldersFolderIdRouteRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdRouteRoute =
  DashboardWorkspaceIdDecksDeckIdRouteRouteImport.update({
    id: '/decks/$deckId',
    path: '/decks/$deckId',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdFoldersFolderIdIndexRoute =
  DashboardWorkspaceIdFoldersFolderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdFoldersFolderIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdIndexRoute =
  DashboardWorkspaceIdDecksDeckIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdRouteRoute,
  } as any)
const DashboardWorkspaceIdFoldersFolderIdEditRoute =
  DashboardWorkspaceIdFoldersFolderIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardWorkspaceIdFoldersFolderIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdEditRoute =
  DashboardWorkspaceIdDecksDeckIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdReviewRouteRoute =
  DashboardWorkspaceIdDecksDeckIdReviewRouteRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdNotesRouteRoute =
  DashboardWorkspaceIdDecksDeckIdNotesRouteRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdReviewIndexRoute =
  DashboardWorkspaceIdDecksDeckIdReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdReviewRouteRoute,
  } as any)
const DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute =
  DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRouteImport.update({
    id: '/create/$entityKind',
    path: '/create/$entityKind',
    getParentRoute: () => DashboardWorkspaceIdFoldersFolderIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute =
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdReviewRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute =
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdNotesRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute =
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute =
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute =
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () =>
      DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute =
  DashboardWorkspaceIdDecksDeckIdNotesNewKindRouteImport.update({
    id: '/new/$kind',
    path: '/new/$kind',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdNotesRouteRoute,
  } as any)
const DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute =
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/menu': typeof MenuRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdRouteRouteWithChildren
  '/menu/conflicts': typeof MenuConflictsRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/trash': typeof MenuTrashRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/edit': typeof WorkspacesWorkspaceIdEditRoute
  '/dashboard/$workspaceId/': typeof DashboardWorkspaceIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId': typeof DashboardWorkspaceIdDecksDeckIdRouteRouteWithChildren
  '/dashboard/$workspaceId/folders/$folderId': typeof DashboardWorkspaceIdFoldersFolderIdRouteRouteWithChildren
  '/dashboard/$workspaceId/create/$entityKind': typeof DashboardWorkspaceIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/notes': typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/review': typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/edit': typeof DashboardWorkspaceIdDecksDeckIdEditRoute
  '/dashboard/$workspaceId/folders/$folderId/edit': typeof DashboardWorkspaceIdFoldersFolderIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId/': typeof DashboardWorkspaceIdDecksDeckIdIndexRoute
  '/dashboard/$workspaceId/folders/$folderId/': typeof DashboardWorkspaceIdFoldersFolderIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteWithChildren
  '/dashboard/$workspaceId/folders/$folderId/create/$entityKind': typeof DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review/': typeof DashboardWorkspaceIdDecksDeckIdReviewIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind': typeof DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/menu/conflicts': typeof MenuConflictsRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/trash': typeof MenuTrashRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/menu': typeof MenuIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/edit': typeof WorkspacesWorkspaceIdEditRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdIndexRoute
  '/dashboard/$workspaceId/create/$entityKind': typeof DashboardWorkspaceIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/notes': typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/edit': typeof DashboardWorkspaceIdDecksDeckIdEditRoute
  '/dashboard/$workspaceId/folders/$folderId/edit': typeof DashboardWorkspaceIdFoldersFolderIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId': typeof DashboardWorkspaceIdDecksDeckIdIndexRoute
  '/dashboard/$workspaceId/folders/$folderId': typeof DashboardWorkspaceIdFoldersFolderIdIndexRoute
  '/dashboard/$workspaceId/folders/$folderId/create/$entityKind': typeof DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review': typeof DashboardWorkspaceIdDecksDeckIdReviewIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind': typeof DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/menu': typeof MenuRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/boot': typeof BootRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdRouteRouteWithChildren
  '/menu/conflicts': typeof MenuConflictsRoute
  '/menu/settings': typeof MenuSettingsRoute
  '/menu/trash': typeof MenuTrashRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/edit': typeof WorkspacesWorkspaceIdEditRoute
  '/dashboard/$workspaceId/': typeof DashboardWorkspaceIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId': typeof DashboardWorkspaceIdDecksDeckIdRouteRouteWithChildren
  '/dashboard/$workspaceId/folders/$folderId': typeof DashboardWorkspaceIdFoldersFolderIdRouteRouteWithChildren
  '/dashboard/$workspaceId/create/$entityKind': typeof DashboardWorkspaceIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/notes': typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/review': typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/edit': typeof DashboardWorkspaceIdDecksDeckIdEditRoute
  '/dashboard/$workspaceId/folders/$folderId/edit': typeof DashboardWorkspaceIdFoldersFolderIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId/': typeof DashboardWorkspaceIdDecksDeckIdIndexRoute
  '/dashboard/$workspaceId/folders/$folderId/': typeof DashboardWorkspaceIdFoldersFolderIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteWithChildren
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteWithChildren
  '/dashboard/$workspaceId/folders/$folderId/create/$entityKind': typeof DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review/': typeof DashboardWorkspaceIdDecksDeckIdReviewIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind': typeof DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute
  '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/': typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute
  '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/': typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/menu'
    | '/workspaces'
    | '/boot'
    | '/dashboard/$workspaceId'
    | '/menu/conflicts'
    | '/menu/settings'
    | '/menu/trash'
    | '/workspaces/new'
    | '/dashboard/'
    | '/menu/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/edit'
    | '/dashboard/$workspaceId/'
    | '/dashboard/$workspaceId/decks/$deckId'
    | '/dashboard/$workspaceId/folders/$folderId'
    | '/dashboard/$workspaceId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/notes'
    | '/dashboard/$workspaceId/decks/$deckId/review'
    | '/dashboard/$workspaceId/decks/$deckId/edit'
    | '/dashboard/$workspaceId/folders/$folderId/edit'
    | '/dashboard/$workspaceId/decks/$deckId/'
    | '/dashboard/$workspaceId/folders/$folderId/'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId'
    | '/dashboard/$workspaceId/folders/$folderId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/review/'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'
    | '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boot'
    | '/menu/conflicts'
    | '/menu/settings'
    | '/menu/trash'
    | '/workspaces/new'
    | '/dashboard'
    | '/menu'
    | '/workspaces'
    | '/workspaces/$workspaceId/edit'
    | '/dashboard/$workspaceId'
    | '/dashboard/$workspaceId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/notes'
    | '/dashboard/$workspaceId/decks/$deckId/edit'
    | '/dashboard/$workspaceId/folders/$folderId/edit'
    | '/dashboard/$workspaceId/decks/$deckId'
    | '/dashboard/$workspaceId/folders/$folderId'
    | '/dashboard/$workspaceId/folders/$folderId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/review'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'
    | '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/menu'
    | '/workspaces'
    | '/boot'
    | '/dashboard/$workspaceId'
    | '/menu/conflicts'
    | '/menu/settings'
    | '/menu/trash'
    | '/workspaces/new'
    | '/dashboard/'
    | '/menu/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/edit'
    | '/dashboard/$workspaceId/'
    | '/dashboard/$workspaceId/decks/$deckId'
    | '/dashboard/$workspaceId/folders/$folderId'
    | '/dashboard/$workspaceId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/notes'
    | '/dashboard/$workspaceId/decks/$deckId/review'
    | '/dashboard/$workspaceId/decks/$deckId/edit'
    | '/dashboard/$workspaceId/folders/$folderId/edit'
    | '/dashboard/$workspaceId/decks/$deckId/'
    | '/dashboard/$workspaceId/folders/$folderId/'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId'
    | '/dashboard/$workspaceId/folders/$folderId/create/$entityKind'
    | '/dashboard/$workspaceId/decks/$deckId/review/'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'
    | '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
    | '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/'
    | '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MenuRouteRoute: typeof MenuRouteRouteWithChildren
  WorkspacesRouteRoute: typeof WorkspacesRouteRouteWithChildren
  BootRoute: typeof BootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRouteRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRouteRoute
    }
    '/menu/trash': {
      id: '/menu/trash'
      path: '/trash'
      fullPath: '/menu/trash'
      preLoaderRoute: typeof MenuTrashRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/menu/settings': {
      id: '/menu/settings'
      path: '/settings'
      fullPath: '/menu/settings'
      preLoaderRoute: typeof MenuSettingsRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/menu/conflicts': {
      id: '/menu/conflicts'
      path: '/conflicts'
      fullPath: '/menu/conflicts'
      preLoaderRoute: typeof MenuConflictsRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/dashboard/$workspaceId': {
      id: '/dashboard/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/dashboard/$workspaceId'
      preLoaderRoute: typeof DashboardWorkspaceIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$workspaceId/': {
      id: '/dashboard/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/'
      preLoaderRoute: typeof DashboardWorkspaceIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/edit': {
      id: '/workspaces/$workspaceId/edit'
      path: '/$workspaceId/edit'
      fullPath: '/workspaces/$workspaceId/edit'
      preLoaderRoute: typeof WorkspacesWorkspaceIdEditRouteImport
      parentRoute: typeof WorkspacesRouteRoute
    }
    '/dashboard/$workspaceId/create/$entityKind': {
      id: '/dashboard/$workspaceId/create/$entityKind'
      path: '/create/$entityKind'
      fullPath: '/dashboard/$workspaceId/create/$entityKind'
      preLoaderRoute: typeof DashboardWorkspaceIdCreateEntityKindRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/folders/$folderId': {
      id: '/dashboard/$workspaceId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/dashboard/$workspaceId/folders/$folderId'
      preLoaderRoute: typeof DashboardWorkspaceIdFoldersFolderIdRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId': {
      id: '/dashboard/$workspaceId/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/dashboard/$workspaceId/decks/$deckId'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/folders/$folderId/': {
      id: '/dashboard/$workspaceId/folders/$folderId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/folders/$folderId/'
      preLoaderRoute: typeof DashboardWorkspaceIdFoldersFolderIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdFoldersFolderIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/': {
      id: '/dashboard/$workspaceId/decks/$deckId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRoute
    }
    '/dashboard/$workspaceId/folders/$folderId/edit': {
      id: '/dashboard/$workspaceId/folders/$folderId/edit'
      path: '/edit'
      fullPath: '/dashboard/$workspaceId/folders/$folderId/edit'
      preLoaderRoute: typeof DashboardWorkspaceIdFoldersFolderIdEditRouteImport
      parentRoute: typeof DashboardWorkspaceIdFoldersFolderIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/edit': {
      id: '/dashboard/$workspaceId/decks/$deckId/edit'
      path: '/edit'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/edit'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdEditRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/review': {
      id: '/dashboard/$workspaceId/decks/$deckId/review'
      path: '/review'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/review'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/notes': {
      id: '/dashboard/$workspaceId/decks/$deckId/notes'
      path: '/notes'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/notes'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/review/': {
      id: '/dashboard/$workspaceId/decks/$deckId/review/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/review/'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRoute
    }
    '/dashboard/$workspaceId/folders/$folderId/create/$entityKind': {
      id: '/dashboard/$workspaceId/folders/$folderId/create/$entityKind'
      path: '/create/$entityKind'
      fullPath: '/dashboard/$workspaceId/folders/$folderId/create/$entityKind'
      preLoaderRoute: typeof DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRouteImport
      parentRoute: typeof DashboardWorkspaceIdFoldersFolderIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/review/$reviewId': {
      id: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId'
      path: '/$reviewId'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/notes/$noteId': {
      id: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId'
      path: '/$noteId'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/': {
      id: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/': {
      id: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary': {
      id: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
      path: '/summary'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/review/$reviewId/summary'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind': {
      id: '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind'
      path: '/new/$kind'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/notes/new/$kind'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNewKindRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRoute
    }
    '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit': {
      id: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'
      path: '/edit'
      fullPath: '/dashboard/$workspaceId/decks/$deckId/notes/$noteId/edit'
      preLoaderRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRouteImport
      parentRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute
    }
  }
}

interface DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteChildren {
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute
}

const DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteChildren: DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteChildren =
  {
    DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute:
      DashboardWorkspaceIdDecksDeckIdNotesNoteIdEditRoute,
    DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute:
      DashboardWorkspaceIdDecksDeckIdNotesNoteIdIndexRoute,
  }

const DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteWithChildren =
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteChildren,
  )

interface DashboardWorkspaceIdDecksDeckIdNotesRouteRouteChildren {
  DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteWithChildren
  DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute
}

const DashboardWorkspaceIdDecksDeckIdNotesRouteRouteChildren: DashboardWorkspaceIdDecksDeckIdNotesRouteRouteChildren =
  {
    DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRoute:
      DashboardWorkspaceIdDecksDeckIdNotesNoteIdRouteRouteWithChildren,
    DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute:
      DashboardWorkspaceIdDecksDeckIdNotesNewKindRoute,
  }

const DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren =
  DashboardWorkspaceIdDecksDeckIdNotesRouteRoute._addFileChildren(
    DashboardWorkspaceIdDecksDeckIdNotesRouteRouteChildren,
  )

interface DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteChildren {
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute
}

const DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteChildren: DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteChildren =
  {
    DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute:
      DashboardWorkspaceIdDecksDeckIdReviewReviewIdSummaryRoute,
    DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute:
      DashboardWorkspaceIdDecksDeckIdReviewReviewIdIndexRoute,
  }

const DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteWithChildren =
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteChildren,
  )

interface DashboardWorkspaceIdDecksDeckIdReviewRouteRouteChildren {
  DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteWithChildren
  DashboardWorkspaceIdDecksDeckIdReviewIndexRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewIndexRoute
}

const DashboardWorkspaceIdDecksDeckIdReviewRouteRouteChildren: DashboardWorkspaceIdDecksDeckIdReviewRouteRouteChildren =
  {
    DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRoute:
      DashboardWorkspaceIdDecksDeckIdReviewReviewIdRouteRouteWithChildren,
    DashboardWorkspaceIdDecksDeckIdReviewIndexRoute:
      DashboardWorkspaceIdDecksDeckIdReviewIndexRoute,
  }

const DashboardWorkspaceIdDecksDeckIdReviewRouteRouteWithChildren =
  DashboardWorkspaceIdDecksDeckIdReviewRouteRoute._addFileChildren(
    DashboardWorkspaceIdDecksDeckIdReviewRouteRouteChildren,
  )

interface DashboardWorkspaceIdDecksDeckIdRouteRouteChildren {
  DashboardWorkspaceIdDecksDeckIdNotesRouteRoute: typeof DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren
  DashboardWorkspaceIdDecksDeckIdReviewRouteRoute: typeof DashboardWorkspaceIdDecksDeckIdReviewRouteRouteWithChildren
  DashboardWorkspaceIdDecksDeckIdEditRoute: typeof DashboardWorkspaceIdDecksDeckIdEditRoute
  DashboardWorkspaceIdDecksDeckIdIndexRoute: typeof DashboardWorkspaceIdDecksDeckIdIndexRoute
}

const DashboardWorkspaceIdDecksDeckIdRouteRouteChildren: DashboardWorkspaceIdDecksDeckIdRouteRouteChildren =
  {
    DashboardWorkspaceIdDecksDeckIdNotesRouteRoute:
      DashboardWorkspaceIdDecksDeckIdNotesRouteRouteWithChildren,
    DashboardWorkspaceIdDecksDeckIdReviewRouteRoute:
      DashboardWorkspaceIdDecksDeckIdReviewRouteRouteWithChildren,
    DashboardWorkspaceIdDecksDeckIdEditRoute:
      DashboardWorkspaceIdDecksDeckIdEditRoute,
    DashboardWorkspaceIdDecksDeckIdIndexRoute:
      DashboardWorkspaceIdDecksDeckIdIndexRoute,
  }

const DashboardWorkspaceIdDecksDeckIdRouteRouteWithChildren =
  DashboardWorkspaceIdDecksDeckIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdDecksDeckIdRouteRouteChildren,
  )

interface DashboardWorkspaceIdFoldersFolderIdRouteRouteChildren {
  DashboardWorkspaceIdFoldersFolderIdEditRoute: typeof DashboardWorkspaceIdFoldersFolderIdEditRoute
  DashboardWorkspaceIdFoldersFolderIdIndexRoute: typeof DashboardWorkspaceIdFoldersFolderIdIndexRoute
  DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute: typeof DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute
}

const DashboardWorkspaceIdFoldersFolderIdRouteRouteChildren: DashboardWorkspaceIdFoldersFolderIdRouteRouteChildren =
  {
    DashboardWorkspaceIdFoldersFolderIdEditRoute:
      DashboardWorkspaceIdFoldersFolderIdEditRoute,
    DashboardWorkspaceIdFoldersFolderIdIndexRoute:
      DashboardWorkspaceIdFoldersFolderIdIndexRoute,
    DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute:
      DashboardWorkspaceIdFoldersFolderIdCreateEntityKindRoute,
  }

const DashboardWorkspaceIdFoldersFolderIdRouteRouteWithChildren =
  DashboardWorkspaceIdFoldersFolderIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdFoldersFolderIdRouteRouteChildren,
  )

interface DashboardWorkspaceIdRouteRouteChildren {
  DashboardWorkspaceIdIndexRoute: typeof DashboardWorkspaceIdIndexRoute
  DashboardWorkspaceIdDecksDeckIdRouteRoute: typeof DashboardWorkspaceIdDecksDeckIdRouteRouteWithChildren
  DashboardWorkspaceIdFoldersFolderIdRouteRoute: typeof DashboardWorkspaceIdFoldersFolderIdRouteRouteWithChildren
  DashboardWorkspaceIdCreateEntityKindRoute: typeof DashboardWorkspaceIdCreateEntityKindRoute
}

const DashboardWorkspaceIdRouteRouteChildren: DashboardWorkspaceIdRouteRouteChildren =
  {
    DashboardWorkspaceIdIndexRoute: DashboardWorkspaceIdIndexRoute,
    DashboardWorkspaceIdDecksDeckIdRouteRoute:
      DashboardWorkspaceIdDecksDeckIdRouteRouteWithChildren,
    DashboardWorkspaceIdFoldersFolderIdRouteRoute:
      DashboardWorkspaceIdFoldersFolderIdRouteRouteWithChildren,
    DashboardWorkspaceIdCreateEntityKindRoute:
      DashboardWorkspaceIdCreateEntityKindRoute,
  }

const DashboardWorkspaceIdRouteRouteWithChildren =
  DashboardWorkspaceIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardWorkspaceIdRouteRoute: typeof DashboardWorkspaceIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardWorkspaceIdRouteRoute: DashboardWorkspaceIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MenuRouteRouteChildren {
  MenuConflictsRoute: typeof MenuConflictsRoute
  MenuSettingsRoute: typeof MenuSettingsRoute
  MenuTrashRoute: typeof MenuTrashRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteRouteChildren: MenuRouteRouteChildren = {
  MenuConflictsRoute: MenuConflictsRoute,
  MenuSettingsRoute: MenuSettingsRoute,
  MenuTrashRoute: MenuTrashRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteRouteWithChildren = MenuRouteRoute._addFileChildren(
  MenuRouteRouteChildren,
)

interface WorkspacesRouteRouteChildren {
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  WorkspacesWorkspaceIdEditRoute: typeof WorkspacesWorkspaceIdEditRoute
}

const WorkspacesRouteRouteChildren: WorkspacesRouteRouteChildren = {
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  WorkspacesWorkspaceIdEditRoute: WorkspacesWorkspaceIdEditRoute,
}

const WorkspacesRouteRouteWithChildren = WorkspacesRouteRoute._addFileChildren(
  WorkspacesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MenuRouteRoute: MenuRouteRouteWithChildren,
  WorkspacesRouteRoute: WorkspacesRouteRouteWithChildren,
  BootRoute: BootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
