// This file is generated by mockapi.
// Do not edit by hand.

import { defineConfig } from '@hey-api/openapi-ts'

const plugins = [
  {
    name: '@hey-api/typescript',
  },
  {
    definitions: true,
    name: 'zod',
    requests: false,
    responses: true,
  },
] as const

export default defineConfig([
  {
    input: "../openapi/openapi.yaml",
    output: {
      clean: true,
      module: {
        extension: '.ts',
      },
      path: "src/generated/clear-web-api/contract",
      tsConfigPath: './tsconfig.json',
    },
    plugins,
  },
  {
    input: "./openapi/admin.yaml",
    output: {
      clean: true,
      module: {
        extension: '.ts',
      },
      path: "src/generated/mock-admin/contract",
      tsConfigPath: './tsconfig.json',
    },
    plugins,
  },
])
