// This file is generated by mockapi.
// Do not edit by hand.

import path from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  generateMockRuntimeFiles,
  type RuntimeConfig,
} from './lib/mockRuntimeCodegen.ts'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const packageRoot = path.resolve(dirname, '..')

const runtimeConfigs = [
  {
    openApiRoot: path.resolve(packageRoot, "../openapi/openapi.yaml"),
    outputPath: path.resolve(packageRoot, "src/generated/clear-web-api/mock-runtime.ts"),
  },
  {
    openApiRoot: path.resolve(packageRoot, "./openapi/admin.yaml"),
    outputPath: path.resolve(packageRoot, "src/generated/mock-admin/mock-runtime.ts"),
  },
] as const satisfies readonly RuntimeConfig[]

await generateMockRuntimeFiles(runtimeConfigs)
